-- MySQL Database Schema for SH-TOP-UP-BD  --

-- Users Table  CREATE TABLE users ( id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, email VARCHAR(100) NOT NULL UNIQUE, created_at DATETIME DEFAULT CURRENT_TIMESTAMP );

-- Packages Table  CREATE TABLE packages ( id INT AUTO_INCREMENT PRIMARY KEY, package_name VARCHAR(100) NOT NULL, price DECIMAL(10, 2) NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP );

-- Orders Table  CREATE TABLE orders ( id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, package_id INT NOT NULL, order_date DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (package_id) REFERENCES packages(id) );

-- Admin Table  CREATE TABLE admin ( id INT AUTO_INCREMENT PRIMARY KEY, admin_username VARCHAR(50) NOT NULL UNIQUE, admin_password VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP );